# Generated by Django 3.0.3 on 2020-10-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=24, verbose_name='Title of the the stat limited to 24 Character')),
                ('stat_value', models.IntegerField()),
                ('units_field', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
