# Generated by Django 3.0.3 on 2020-10-14 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statitem',
            name='data_delay',
            field=models.IntegerField(blank=True, default=2, verbose_name='Total Animation Time'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='data_increment',
            field=models.IntegerField(blank=True, default=1, verbose_name='Incrementor step'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='data_max',
            field=models.IntegerField(default=0, verbose_name='Reaching Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statitem',
            name='data_min',
            field=models.IntegerField(blank=True, default=0, verbose_name='Starting Value'),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
