# Generated by Django 3.0.3 on 2020-12-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of landing section of the Home page')),
                ('description', models.TextField(verbose_name='Paragraph of the landing section of the Home page')),
            ],
        ),
    ]
