# Generated by Django 3.0.3 on 2020-03-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
