# Generated by Django 3.0.3 on 2020-09-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('desc', models.TextField(blank=True)),
                ('image_1', models.ImageField(blank=True, upload_to='uploaded_images')),
                ('alt_1', models.CharField(blank=True, max_length=400)),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('alt_2', models.CharField(blank=True, max_length=400)),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('alt_3', models.CharField(blank=True, max_length=400)),
                ('image_4', models.ImageField(blank=True, upload_to='')),
                ('alt_4', models.CharField(blank=True, max_length=400)),
                ('published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
