# Generated by Django 3.0.3 on 2020-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='alt_1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='news',
            name='alt_2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='news',
            name='alt_3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='news',
            name='alt_4',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='news',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
