# Generated by Django 3.0.3 on 2020-12-05 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20200424_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
