# Generated by Django 3.0.3 on 2020-04-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='phone_num',
        ),
    ]
