# Generated by Django 3.0.3 on 2020-11-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0002_remove_donor_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=75)),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
