# Generated by Django 3.0.3 on 2020-03-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200321_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
