# Generated by Django 3.0.3 on 2020-12-05 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
