# Generated by Django 3.0.3 on 2021-03-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20201205_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.TextField(default='A new KindnessCafe news!'),
        ),
    ]
